sudo: required

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

language: python
python:
  # We don't actually use the Travis Python (since we are on conda), but this keeps it organized.
  - "3.6"

before_install:
  # Temporal fix for networking problem: https://github.com/travis-ci/travis-ci/issues/1484
  - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts

  # The next couple lines fix a crash with multiprocessing on Travis and
  # are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  # Get and install anaconda (https://conda.io/docs/travis.html)
  - wget -nv https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Installing umccrise packages
  - conda env create -n umccrise --file environment.yml
  - source activate umccrise
  # Useful for debugging any issues with conda
  - conda info -a
  # Installing the codebase (source code was automatically cloned into CWD by Travis)
  - pip install -e .
  - R -e "library(devtools) ; options(unzip = '/usr/bin/unzip') ; devtools::install_github('umccr/rock')"

script:
  - nosetests --nocapture tests/test.py -a normal
  - rm -rf $HOME/miniconda
  - docker version
  - docker build -t umccr/umccrise:latest -f Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
  - docker push umccr/umccrise:latest
  # Commenting out because travis time exceeding on building umccr/umccrise:with_test_data
  # - docker build -t umccr/umccrise:with_test_data -f Dockerfile.with_test_data .
  # - docker push umccr/umccrise:with_test_data

#notifications:
#  on_success: always
#  email: false
#  slack:
#    rooms:
