sudo: required
dist: trusty

language: python
python:
  - "3.6"

install:
  - docker build -t umccr/umccrise -f Dockerfile .
  - git clone https://github.com/umccr/umccrise_test_data $HOME/umccrise_test_data

script:
  - docker run -t --cpus 1 umccr/umccrise umccrise --version
#  - docker run -t --cpus 1
#    -v=$HOME/umccrise_test_data/results/bcbio_test_project_docker:/output_dir
#    -v=$HOME/umccrise_test_data/data/bcbio_test_project:/bcbio_project
#    -v=$HOME/umccrise_test_data/data/genomes:/genomes
#    umccr/umccrise
#    umccrise /bcbio_project -o /output_dir structural

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

deploy:
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin &&
            docker tag umccr/umccrise umccr/umccrise:$TRAVIS_TAG
            docker push umccr/umccrise:$TRAVIS_TAG
    on:
      tags: true
    skip_cleanup: true
