version: 0.2
run-as: root
env:
    variables:
        "ECR": "620123204273.dkr.ecr.ap-southeast-2.amazonaws.com/umccrise"
        "S3_REFDATA_BUCKET": "umccr-umccrise-refdata-dev"
    parameter-store:
        "UMCCR_DOCKERHUB_USER": "/CodeBuild/UMCCR_DOCKERHUB_USER"
        "UMCCR_DOCKERHUB_PASSWORD": "/CodeBuild/UMCCR_DOCKERHUB_PASSWORD"
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
        - apk add --no-cache python3
        - apk add --no-cache git
        - pip3 install --no-cache --upgrade pip
        - pip3 install --no-cache --upgrade awscli
  build:
    commands:
        # Docker-in-docker bizarre AWS stuff: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
        - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
        - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
        # Convenience CODEBUILD VARS, need more? Check https://github.com/thii/aws-codebuild-extras
        - export SHORT_COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
        - export CODEBUILD_GIT_TAG="$(git describe --tags --exact-match 2>/dev/null)"
        # Build and tag (-t) image
        - docker build -t $ECR:$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH -f Dockerfile .
  post_build:
    commands:
      # Run tests
      - git clone https://github.com/umccr/umccrise_test_data umccrise_test_data
      - mkdir -p /work/genomes && time aws s3 sync --only-show-errors s3://$S3_REFDATA_BUCKET/genomes/ /work/genomes
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
      - docker run -t --cpus 2 -v=$PWD/umccrise_test_data/results/bcbio_test_project_docker:/output_dir
        -v=$PWD/umccrise_test_data/data/bcbio_test_project:/bcbio_project
        -v=$PWD/umccrise_test_data/data/genomes:/work/genomes
        $ECR:$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH umccrise /bcbio_project -o /output_dir --genomes /work/genomes --no-igv
      # Push the container to ECR if tests pass
      - docker push $ECR:$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH
