version: 0.2
run-as: root
env:
    parameter-store:
        "UMCCR_DOCKERHUB_USER": "/CodeBuild/UMCCR_DOCKERHUB_USER"
        "UMCCR_DOCKERHUB_PASSWORD": "/CodeBuild/UMCCR_DOCKERHUB_PASSWORD"
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  build:
    commands:
        # - apt-get install -y git
        # - git clone https://github.com/umccr/umccrise_test_data umccrise_test_data
        # Docker-in-docker bizarre AWS stuff: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
        - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
        - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
        - docker build -t umccr/umccrise -f Dockerfile .
  post_build:
    commands:
      - echo "$UMCCR_DOCKERHUB_PASSWORD" | docker login --username "$UMCCR_DOCKERHUB_USER" --password-stdin
      - docker tag umccr/umccrise umccr/umccrise:"$CODEBUILD_SOURCE_VERSION"
      - docker push umccr/umccrise:"$CODEBUILD_SOURCE_VERSION"
