version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
        - docker build -t umccr/umccrise -f Dockerfile .
        - git clone https://github.com/umccr/umccrise_test_data umccrise_test_data
#  build:
#    commands:
#      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
#      - docker tag umccr/umccrise umccr/umccrise:$CODEBUILD_SOURCE_VERSION
