version: 0.2
run-as: root
env:
    variables:
        "ECR": "620123204273.dkr.ecr.ap-southeast-2.amazonaws.com/umccrise"
    parameter-store:
        "UMCCR_DOCKERHUB_USER": "/CodeBuild/UMCCR_DOCKERHUB_USER"
        "UMCCR_DOCKERHUB_PASSWORD": "/CodeBuild/UMCCR_DOCKERHUB_PASSWORD"
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
        - apk add --no-cache python3
        - pip3 install --no-cache --upgrade pip
        - pip install --upgrade awscli

  build:
    commands:
        # Docker-in-docker bizarre AWS stuff: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
        - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
        - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
        - docker build -t umccr/umccrise -f Dockerfile .
  post_build:
    commands:
      - export SHORT_COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
      - echo $SHORT_COMMIT_HASH
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
      - docker tag umccr/umccrise $ECR:$SHORT_COMMIT_HASH
      - docker push $ECR:$SHORT_COMMIT_HASH

# XXX: test phase, codepipeline
# - git clone https://github.com/umccr/umccrise_test_data umccrise_test_data
