version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
    commands:
        - su -
        - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
        - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
        - id && cat /etc/passwd && cat /etc/group && ls /var/lib/ && ps aux | grep docker
        - whoami
        - docker build -t umccr/umccrise -f Dockerfile .
        - git clone https://github.com/umccr/umccrise_test_data umccrise_test_data
#  build:
#    commands:
#      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
#      - docker tag umccr/umccrise umccr/umccrise:$CODEBUILD_SOURCE_VERSION
