name: umccrise

channels:
  - bioconda
  - conda-forge
  - defaults
  - vladsaveliev
  - anaconda

dependencies:
  - python>=3.6
  - bcftools
  - tabix
  - bedops
  - bedtools
  - vcfanno
  - vcflib  # for VCF normalisation
  - snakemake
  - pythonpy
  - click
  - cyvcf2
  - pandas
  #
  # Umccrise-specific
  - goleft
  - awscli
  - pyasn1  # for awscli - for some reason doesn't install automatically on macos
  - cnvkit
  # R libraries
  - pandoc<2  # r-rmarkdown 1.6 doesn't support pandoc 2, and a more recent r-rmarkdown is not available on conda
  - r
  - r-rmarkdown
  - r-ggplot2
  - r-tidyr
  - r-dt
  - bioconductor-delayedarray
  - bioconductor-summarizedexperiment>=1.8
  - bioconductor-mutationalpatterns
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - r-devtools
  - r-readr
  - r-stringr
  - pip:
    - "--editable=git+https://github.com/vladsaveliev/NGS_Utils#egg=ngs_utils"
    - "--editable=git+https://github.com/umccr/python_utils#egg=python_utils"
    - "--editable=git+https://github.com/umccr/vcf_stuff#egg=vcf_stuff"