name: umccrise

channels:
  - bioconda
  - conda-forge
  - defaults
  - vladsaveliev

dependencies:
  - python>=3.6
  - bcftools
  - tabix
  - bedops
  - bedtools
  - vcfanno
  - vcflib
  - snakemake
  - pythonpy
  - goleft
  - break-point-inspector
  - pandoc<2  # r-rmarkdown 1.6 doesn't support pandoc 2, and a more recent r-rmarkdown is not available on conda
  #
  # Python libraries
  - cyvcf2
  - ngs_utils
  - click
  - cnvkit
  - pandas
  #
  # R libraries
  - r
  - r-rmarkdown
  - r-ggplot2
  - r-tidyr
  - r-dt
  - bioconductor-delayedarray
  - bioconductor-summarizedexperiment>=1.8
  - bioconductor-mutationalpatterns
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - r-devtools
  - r-readr
  - r-stringr