name: umccrise

channels:
  - vladsaveliev
  - bioconda
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - python>=3.6
  - bcftools
  - tabix
  - bedtools
  - vcfanno
  - vcflib  # for VCF normalisation
  - pythonpy
  - click
  - cyvcf2
  - numpy
  - pandas
  - curl>=7.59  # to make sure libcurl.4.dylib>=10.0.0 is installed
  #
  # Umccrise-specific
  - goleft
  - awscli
  - pyasn1  # for awscli - for some reason doesn't install automatically on macos
  - cnvkit
  # R libraries
  - pandoc<2  # r-rmarkdown 1.6 doesn't support pandoc 2, and a more recent r-rmarkdown is not available on conda
  - r
  - r-rmarkdown
  - r-ggplot2
  - r-tidyr
  - r-dt
  - bioconductor-delayedarray
  - bioconductor-summarizedexperiment>=1.8
  - bioconductor-mutationalpatterns
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - r-devtools
  - r-readr
  - r-stringr
  - r-htmlwidgets>=1.0  # dependency requirement for DT (by default, 0.9 is getting installed)
  - snakemake>=5.1.2vlad
  - ngs_utils>=2.0.4
  #
  # Matplotlib deps (without QT)
#  - cycler >=0.10
#  - python-dateutil
#  - freetype 2.8.*
#  - pytz
#  - pyparsing
#  - libpng >=1.6.32,<1.6.35
#  - tk 8.6.*
#  - icu 58.*
#  - tornado
#  - kiwisolver
  #
  # Actively developed accompanying libraries
  - pip:
    - "--editable=git+https://github.com/umccr/python_utils#egg=python_utils"
    - "--editable=git+https://github.com/umccr/vcf_stuff#egg=vcf_stuff"
