name: umccrise

channels:
  - vladsaveliev
  - bioconda
  - conda-forge

dependencies:
  - python>3.6
  - bcftools
  - tabix
  - bedops
  - bedtools
  - vcfanno
  - vcflib
  - snakemake
  - pythonpy
  - goleft
  - break-point-inspector
  - pandoc
  #
  # Python libraries
  - cyvcf2
  - ngs_utils
  - click
  - cnvkit
  - pandas
  #
  # R libraries
  - r
  - r-rmarkdown
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-raster
  - r-dt
  - r-mutationalpatterns
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - r-devtools
