---
- name: install python devel
  become: true
  package:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  with_items:
      - build-essential
      - python-dev

- name: clone umccrise
  git:
    repo: "https://github.com/brainstorm/umccrise"
    version: "deploy"
    dest: /home/ubuntu/umccrise

- name: install umccrise 
  command: /usr/local/anaconda/bin/conda env create --file /home/ubuntu/umccrise/environment.yml
