max_table_rows: 500
plots_flat_numseries: 300
no_version_check: True
template: 'umccr'
#read_count_multiplier: 0.001
#read_count_prefix: 'k'
#read_count_desc: ' thousand'
base_count_multiplier: 0.000000001
base_count_prefix: 'Gb'
base_count_desc: 'gigabases'
make_data_dir: False


# high values push to the right, default is 1000: https://multiqc.info/docs/#column-order
table_columns_placement:
    bcbio:
        viral_content: 2000  # to put it in the end


# Overwrite the defaults of which table columns are visible by default
table_columns_visible:
    FastQC:
        percent_gc: False
        percent_duplicates: False                 # is also set in bcbio/__init__.py
        total_sequences: False                    # is also set in bcbio/__init__.py
        avg_sequence_length: False                # is also set in bcbio/__init__.py
    QualiMap:
        reads_aligned: False
        percentage_aligned: False                 # is also set in bcbio/__init__.py
        median_coverage: False                    # is also set in bcbio/__init__.py
    Samtools Stats:
        non-primary_alignments_percent: True
        non-primary_alignments: False             # is also set in bcbio/__init__.py
        reads_mapped: False                       # is also set in bcbio/__init__.py
        reads_mapped_percent: False               # is also set in bcbio/__init__.py
        raw_total_sequences: False                # is also set in bcbio/__init__.py
        error_rate: False                         # is also set in bcbio/__init__.py
        reads_properly_paired_percent: True
        reads_MQ0_percent: True
    bcbio:
        Usable_pct: False
        Ontarget_padded_pct: False
        Average_insert_size: False
        RiP_pct: False
    SnpEff:
        Change_rate: False                        # is also set in bcbio/__init__.py
        Ts_Tv_ratio: False                        # is also set in bcbio/__init__.py
        Number_of_variants_before_filter: False   # is also set in bcbio/__init__.py
    Bcftools Stats:
        number_of_SNPs: True
        number_of_indels: True
        tstv: True
        number_of_records: True
        variations_hom: True
        variations_het: True
        number_of_MNPs: True
        number_of_others: True
    Peddy:
        family_id: False
        ancestry-prediction: True
        ancestry-prob_het_check: False
        sex_het_ratio: False
        error_sex_check: False
        error: False
    VerifyBAMID:
        Contam: False
    mosdepth:
#        30_x_pc: False
        median_coverage: False

bcftools:
    collapse_complementary_changes: False
    write_general_stats: False
    write_separate_table: True

qualimap:
    general_stats_coverage: 1, 5, 10, 30, 100

umccr:
    reference_samples:
    - Alice
    - Bob
    - Chen
    - Dakota
    - Elon
    - Alice_T
    - Bob_T
    - Chen_T
    - Dakota_T
    - Elon_T
    - Alice_B
    - Bob_B
    - Chen_B
    - Dakota_B
    - Elon_B
    - Alice_normal
    - Bob_normal
    - Chen_normal
    - Dakota_normal
    - Elon_normal
    - Alice_N
    - Bob_N
    - Chen_N
    - Dakota_N
    - Elon_N

module_order:
    - bcbio
    - samtools
    - goleft_indexcov
    - peddy
    - custom_content
    - bcftools:
        info: Bcftools stats for somatic variant calls.
        name: Bcftools stats (somatic)
        path_filters:
        - '*_bcftools_stats.txt'
        write_general_stats: true
    - bcftools:
        info: Bcftools stats for germline variant calls.
        name: Bcftools stats (germline)
        path_filters:
        - '*_bcftools_stats_germline.txt'
        write_general_stats: false
    - picard
    - qualimap
    - snpeff
    - fastqc
    - preseq

custom_data:
    umccrise:
# ID, section_name, description work only for plots and separate tables (plot_type: "table").
# Do not specify them for generalstats otherwise it won't show up :(
#        id: somatic_stats
#        section_name: 'Somatic variants'
#        description: 'Somatic variant calls, pre- and post-filtered statistics'
        plot_type: generalstats
        pconfig:

        - subset_genes:
            title: 'Subset to key genes'
            description: 'Percentage of variants removed by subsetting to cancer genes. This happens when there are more than 500k calls to avoid choking the reporting'
            min: 0
            max: 100
            format: '{:,.2f}'
            suffix: '%'

        - filt_snps:
            title: 'SNP-filt'
            description: '% SNPs filtered out by somatic filters (panel of normals, gnomAD common, homopolymers/LCR with low depth and AF)'
            min: 0
            max: 100
            format: '{:,.2f}'
            scale: 'Reds'
            suffix: '%'
        - filt_indels:
            title: 'Indel-filt'
            description: '% Indels filtered out by somatic filters (panel of normals, gnomAD common, homopolymers/LCR with low depth and AF)'
            min: 0
            max: 100
            format: '{:,.2f}'
            scale: 'Reds'
            suffix: '%'
        - filt_other:
            title: 'Other-filt'
            description: '% Other variants (MNP) filtered out by somatic filters (panel of normals, gnomAD common, homopolymers/LCR with low depth and AF)'
            min: 0
            max: 100
            format: '{:,.2f}'
            scale: 'Reds'
            suffix: '%'

        - snps:
            title: 'SNP'
            description: 'Somatic SNPs passing umccrise filters'
            min: 0
            format: '{:,.0f}'
        - indels:
            title: 'Indel'
            description: 'Somatic indels passing umccrise filters'
            min: 0
            format: '{:,.0f}'
        - other:
            title: 'Other'
            description: 'Other somatic variants (MNP), passing umccrise filters'
            min: 0
            format: '{:,.0f}'

#        - ori_snps:
#            title: 'SNP-ori'
#            description: 'Total SNPs called by bcbio, that were a subject to subsetting to cancer genes in order to continue filtering because exceeding the number of 500k (possible a contaminated or low quality sample)'
#            min: 0
#            format: '{:,.0f}'
#        - ori_indels:
#            title: 'Indel-ori'
#            description: 'Total indels called by bcbio, that were a subject to subsetting to cancer genes in order to continue filtering because exceeding the number of 500k (possible a contaminated or low quality sample)'
#            min: 0
#            format: '{:,.0f}'
#        - ori_other:
#            title: 'Other-ori'
#            description: 'Total orther variants (MNP) called by bcbio, that were a subject to subsetting to cancer genes in order to continue filtering because exceeding the number of 500k (possible a contaminated or low quality sample)'
#            min: 0
#            format: '{:,.0f}'

        - germline:
            title: 'Germline'
            description: 'Germline variants (from normal sample)'
            min: 0
            format: '{:,.0f}'

#        - pon:
#            title: 'PoN'
#            description: 'Variants filtered out because they found in the UMCCR panel of normals'
#            id: 'pon'
#            min: 0
#        - gnomad:
#            title: 'gnomAD'
#            description: 'Variants filtered out because they found in gnomAD with population AF>1%'
#            id: 'pon'
#            min: 0
#        - pon:
#            title: 'PoN'
#            description: 'Variants found in UMCCR panel of normals'
#            id: 'pon'
#            min: 0
#            max: 100
#            scale: 'RdYlGn'
#            suffix: '%'
#        - pon_filt:
#            title: 'PoN filt'
#            description: 'Variants filtered due to hits in UMCCR panel of normals (filtering threshold - 2 hits, but keeping all hotspots and TIER 1-3)'
#            id: 'pon_filt'
#            min: 0
#            max: 100
#            scale: 'RdYlGn'
#            suffix: '%'
#            hidden: True
#        - hom_het:
#        - ts_tv:

sp:
    umccrise:
        fn_re: '(somatic|germline)_stats.yml'


extra_fn_clean_trim:
    - '-coverage.mosdepth.region.dist'
    - '-coverage.mosdepth.global.dist'












