---
- name: install python and docker essentials
  become: true
  package:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  with_items:
      - python3-pip

- name: Make sure vital python packages are installed system-wide 
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
      - docker-py
      - boto3
      - awscli

- name: "Adding SSH UMCCR team public keys to the instance"
  become: false
  shell: |
      org_ssh_keys=$(curl -s https://api.github.com/orgs/umccr/members | jq -r .[].html_url | sed 's/$/.keys/')
      echo $org_ssh_keys
      for ssh_key in $org_ssh_keys
      do
              wget $ssh_key -O - >> $HOME/.ssh/authorized_keys
      done

- name: clone umccrise
  git:
    repo: "https://github.com/brainstorm/umccrise"
    version: "deploy"
    dest: /home/ubuntu/umccrise

# http://www.pesikov.tk/blog/failed-restart-docker-service-unit-docker-service-masked/
# https://github.com/geerlingguy/ansible-role-docker/issues/60
# https://github.com/docker/for-linux/issues/290#issuecomment-393605253
- name: enable service httpd and ensure it is not masked
  become: true
  systemd:
    name: docker.service
    enabled: yes
    masked: no

- name: enable service httpd and ensure it is not masked
  become: true
  systemd:
    name: docker.socket
    enabled: yes
    masked: no

- name: Add user to docker group
  become: true
  user:
      name: ubuntu
      groups: docker
      append: yes

- name: Pull docker image for UMCCRISE"
  docker_image:
    name: umccr/umccrise
    state: present
