# pcgr_predispose configuration options (TOML).

[secondary_findings]
## Include variants found in ACMG-recommended list for incidental findings
## https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/
show_sf = true

[maf_limits]
## choose upper MAF thresholds for report of unclassified variants
maf_gnomad = 0.05

[popgen]
## choose population source in gnomAD and 1000 Genomes Project, defaults to the global set

## For gnomaAD, this can by any of the following values (three-letter codes):
## "afr" - African/American (12,020 individuals (7,652 WES / 4,368 WGS))
## "amr" - Admixed American (17,210 individuals (16,791 WES / 419 WGS))
## "eas" - East Asian (9,435 individuals (8,624 WES / 811 WGS))
## "sas" - Sout Asian (15,391 individuals (15,391 WES / 0 WGS))
## "asj" - Ashkenazi Jewish (5,076 individuals (4,925 WES / 151 WGS))
## "nfe" - Non-Finnish European (63,369 individuals (55,860 WES / 7,509 WGS))
## "fin" - Finnish (12,897 individuals (11,150 WES / 1,747 WGS))
## "oth" - Other (3,234 individuals (2,743 WES / 491 WGS))
## "global" - All populations (138,632 individuals (123,136 WES / 15,496 WGS))
pop_gnomad = "global"

## For 1000 Genomes Project this can be any of "afr","amr","sas","eas","eur","global"
pop_tgp = "global"

[visual]
# Choose visual theme of report, any of: "default", "cerulean", "journal", "flatly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", or "yeti" (https://bootswatch.com/)
report_theme = "default"

[custom_tags]
## list VCF info tags that should be present in JSON output
## tags should be comma separated, i.e. custom_tags = "GATK_FILTER,VARSCAN_FILTER"
custom_tags = ""

[gwas]
gwas_hits = true
## Required p-value for reporting of GWAS hits
p_value_min = 5e-8

[other]
n_vcfanno_proc = 4
n_vep_forks = 4
vep_skip_intergenic = false
vcf2maf = false
vep_pick_order = "rank,appris,biotype,tsl,ccds,canonical,length,mane"
